[Interface]
PrivateKey = sLPBSsrhzoqZSOY/XxAzGAy5F+sQKQIIE3WoxG8buWM=
Address = 10.2.0.2/32

[Peer]
# Local Direct
PublicKey = mkI+cC9ggzfMdZy1cl3Fl01gPJJxsLXjshXAN8EedQ8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.20.27.53:51820
PersistentKeepalive = 25
AllowedApps = dummy_disabled_app.exe
DisallowedApps = chrome.exe, chrome, msedge.exe, msedge, brave.exe, brave, opera.exe, opera, firefox.exe, firefox, vivaldi.exe, vivaldi, steam.exe, steam, epicgameslauncher.exe
